payum:
  storages:
    Payum\Core\Model\Payment: { doctrine: orm }
  #        Payum\Core\Model\Payment:
  #            filesystem:
  #                storage_dir: '%kernel.root_dir%/Resources/payments'
  #                id_property: number

  security:
    token_storage:
      Payum\Core\Model\Token: { doctrine: orm }
  #            Payum\Core\Model\Token:
  #                filesystem:
  #                    storage_dir: '%kernel.root_dir%/Resources/gateways'
  #                    id_property: hash

  gateways:
    offline:
      factory: offline